[workspace]
name = "ljosbru"
channels = ["conda-forge"]
# https://github.com/conda-forge/zbar-feedstock/issues/2 for win-64
# TODO: add linux-aarch64 https://github.com/conda-forge/zbar-feedstock/pull/17
platforms = ["osx-arm64", "linux-64"]
exclude-newer = "7d"

[tasks]
build = "cargo build"
test = "cargo test"

[dependencies]
rust = "*"
zbar = "*"
pkg-config = "*"

[target.linux.dependencies]
compilers = ">=1.7.0"
wayland = "*"

[feature.lint.dependencies]
pre-commit = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run -a"

[environments]
default = ["lint"]
